#include<stdio.h>

void Display(int);
void Pattern2(int iNo);
void Pattern3(int iNo);
void Pattern4(int iNo);
void Pattern5(int iNo);
void Pattern6(int iNo);
void Pattern7(int iNo);
void Pattern8(int iNo);
void Pattern9(int iNo);
void Pattern10(int iNo);
void Pattern11(int iRows,int iCol);
void Pattern12(int iRows,int iCol);
void Pattern13(int iRows,int iCol);
void Pattern14(int iRows,int iCol);
void Pattern15(int iRows,int iCol);
void Pattern16(int iNo);
void Pattern17(int iRows,int iCol);
void Pattern18(int iRows,int iCol);
void Pattern19(int iRows,int iCol);
void Pattern20(int iRows,int iCol);
void Pattern21(int iRows,int iCol);
void Pattern22(int iRows,int iCol);
void Pattern23(int iRows,int iCol);
void Pattern24(int iRows,int iCol);
void Pattern25(int iRows,int iCol);
void Pattern26(int iRows,int iCol);
void Pattern27(int iRows,int iCol);
void Pattern28(int iRows,int iCol);
void Pattern29(int iRows,int iCol);
void Pattern30(int iRows,int iCol);
void Pattern31(int iRows,int iCol);
void Pattern32(int iRows,int iCol);
void Pattern33(int iRows,int iCol);
void Pattern34(int iRows,int iCol);
void Pattern35(int iRows,int iCol);
void Pattern36(int iRows,int iCol);
void Pattern37(int iRows,int iCol);
void Pattern38(int iRows,int iCol);
void Pattern39(int iRows,int iCol);
void Pattern40(int iRows,int iCol);